import Header from './components/Header/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-light">
      <Header title="Where in the world?" onDarkModeToggle={() => {}} />
        <div className="container">
          <div className="row mx-2">
          {children}
          </div>
        </div>
      </body>
    </html>
  )
}
